name: marathon
description: A framework and collection of packages for writing http servers, built on top of the shelf package.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6
