name: marathon_sessions
description: The Marathon project's module for handling sessions in shelf servers.
version: 0.1.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  marathon: 0.1.1
  marathon_cookies: 0.1.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6
